Uni='uet Lahore'
print(Uni.upper())
print(Uni.lower())
print(Uni.replace("uet", "UCP"))
print(Uni.capitalize())
print(Uni.center(90))
print(Uni.count('e'))
print(Uni.endswith('ore'))
print(Uni.endswith('ore',2,5))
print(Uni.find("aho"))
print(Uni.find("aho", 3, 8))
print(Uni.isalnum())
print(Uni.isalpha())
print(Uni.swapcase())